version: '3.7'
services:
  java-service:
    container_name: otel_demo
    image: cch0124/otel-note-api-demo:latest
    environment:
      OTEL_TRACES_EXPORTER: otlp 
      OTEL_METRICS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://192.168.133.140:4317
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://192.168.133.140:4317
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://192.168.133.140:4317
      OTEL_EXPORTER_OTLP_TIMEOUT: 1000
      OTEL_RESOURCE_ATTRIBUTES: "service.name=java-demo,service.version=v1.0.0"
      OTEL_PROPAGATORS: "tracecontext,baggage"
      OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notes_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: 123456
    ports: 
      - "8000:8080"
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: notes_app
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456

volumes:
  db_data: {}